#!/usr/bin/perl

##############################################
#Perl script takes genome FASTA files and maps 
#to the relevant reference genome. 
#
#############################################

use strict;
use warnings;
use Getopt::Long;
use POSIX;

use Data::Dumper;

my $bowtie;
my $help;
my $index;

my $config_result = GetOptions(
	"bowtie=s" => \$bowtie,
    "index=s" =>  \$index,
	"help" => \$help,
);


if ($help or !@ARGV) {
    print while (<DATA>);
    exit(0);
}

die "Please specify ONE input fasta file" unless (@ARGV == 1);

$bowtie = '/bi/apps/bowtie/0.12.9/bowtie' unless defined $bowtie;
$index = '/bi/scratch/Genomes/Mouse/NCBIM37/Mus_musculus.NCBIM37' unless defined $index;

print "Using Bowtie at: $bowtie\n";
print "Mapping against Bowtie indices: $index\n";

my $command = "$bowtie -m 1 -n 1 --best -p 4 -f --sam --chunkmbs 512 $index $ARGV[0] $ARGV[0].sam";
my $clusterCommand = "echo \"$bowtie -m 1 -n 1 --best -p 4 -f --sam $index $ARGV[0] $ARGV[0].sam\" | qsub -cwd -V -l vf=4G -pe orte 4 -o mapaGen.out -j y -N mapaGen -m eas -M steven.wingett\@babraham.ac.uk";



#!system("$command") or die "Could not execute : $command : $!";
!system("$clusterCommand") or die "Could not execute : $clusterCommand : $!";

print "Processing complete\n";

exit(0);  




__DATA__

SYNOPSIS

Takes the virtual FASTA reads files and maps to the relevant reference genome

mapaGen [OPTIONS]... [VIRTUAL READ FILES]

FUNCTION

Maps the virtual reads file to a specified reference genome using bowtie, with
options similar to that used by HiCUP (HiCUP maps FASTQ files, not FASTA).
Bowtie parameters: -m 1 -n 1 --best -p 4 -f --sam

COMMAND LINE OPTIONS

--bowtie       Path to Bowtie (default: /bi/apps/bowtie/0.12.9/bowtie)
--help         Print help message and exit
--index        Path to Bowtie index files (including basename):
               /bi/scratch/Genomes/Mouse/NCBIM37/Mus_musculus.NCBIM37
